### ISSUE TITLE
Getting error in testsigma agent while registering the ios simulators 

### ISSUE THREAD

**Issue by samagarw** [testsigmahq/testsigma#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the current behavior?

com.testsigma.automator.exceptions.AutomatorException: Cannot run program "idb": error=2, No such file or directory
	at com.testsigma.automator.mobile.ios.IosDeviceCommandExecutor.runDeviceCommand(IosDeviceCommandExecutor.java:56) ~[testsigma-automator-1.0.0.jar:?]
	at com.testsigma.agent.mobile.ios.IosDeviceService.simulatorDeviceList(IosDeviceService.java:107) ~[agent.jar:1.3.0]
	at com.testsigma.agent.schedulers.IOSEmulatorScheduler.run(IOSEmulatorScheduler.java:36) ~[agent.jar:1.3.0]
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Work

Also i have added 5 android devices but agent is showing only 1 device .

Snapshot : 

<img width="279" alt="Screenshot 2022-12-22 at 1 15 37 PM" src="https://user-images.githubusercontent.com/5329851/209083569-4411e2ac-ee39-4fa4-964d-71bb57867503.png">
<img width="1505" alt="Screenshot 2022-12-22 at 1 15 51 PM" src="https://user-images.githubusercontent.com/5329851/209083581-bbbe0aff-b3a0-44d3-8134-71e7b77cee93.png">

### What is the expected behavior?

IOS Simulators should be shown on agents . 

Also all the devices should be shown on the agents . 

### Steps To Reproduce

1. Start testsigma server . 
2. Start agent for mac 
3. Check the devices and browsers 

### Version

Testsigma Community Edition

**Comment by rukmangada** [comment]
+Amit Savyasachi ***@***.***>

Regards,
Rukmangada(KR)
Founder & CEO | Testsigma
https://testsigma.com
<https://mailtrack.io/trace/link/92c8a31714c85e837c3d3d654181f92dde679b1f?url=https%3A%2F%2Ftestsigma.com%2F&userId=4655759&signature=f7f306ce00672331>

**Comment by tarun-testsigma** [comment]
Currently users need to install idb(https://fbidb.io/docs/installation/) in order to work with ios simulators. We will remove this dependency in a future release

**Comment by tarun-testsigma** [comment]
From v2.9 onwards, you dont need to install any dependencies in order to make IOS simulators work. Reopen this if you are having issues in the latest version
